### ISSUE TITLE
GLFW library is not initialized 

### ISSUE THREAD

**Issue by lucdar** [GrooveStats/gslauncher#14]
I'm getting the following error when running the launcher 1.3.2 on Debian 11 compiled using Go 1.18:

```
panic: NotInitialized: The GLFW library is not initialized

goroutine 1 [running, locked to thread]:
github.com/go-gl/glfw/v3.3/glfw.acceptError({0x0, 0x0, 0x886fcbccf18081cc?})
	/home/lucdar/go/pkg/mod/github.com/!groove!stats/go-glfw/v3.3/glfw@v0.0.0-20210815200153-34d2c095d202/error.go:174 +0x185
github.com/go-gl/glfw/v3.3/glfw.panicError(...)
	/home/lucdar/go/pkg/mod/github.com/!groove!stats/go-glfw/v3.3/glfw@v0.0.0-20210815200153-34d2c095d202/error.go:185
github.com/go-gl/glfw/v3.3/glfw.CreateStandardCursor(0x915e20?)
	/home/lucdar/go/pkg/mod/github.com/!groove!stats/go-glfw/v3.3/glfw@v0.0.0-20210815200153-34d2c095d202/input.go:530 +0x45
fyne.io/fyne/v2/internal/driver/glfw.initCursors()
	/home/lucdar/go/pkg/mod/fyne.io/fyne/v2@v2.1.4/internal/driver/glfw/window.go:43 +0x5f
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).initGLFW.func1()
	/home/lucdar/go/pkg/mod/fyne.io/fyne/v2@v2.1.4/internal/driver/glfw/loop.go:105 +0x54
sync.(*Once).doSlow(0x203000?, 0x203000?)
	/usr/lib/go-1.18/src/sync/once.go:68 +0xc2
sync.(*Once).Do(...)
	/usr/lib/go-1.18/src/sync/once.go:59
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).initGLFW(0x829286?)
	/home/lucdar/go/pkg/mod/fyne.io/fyne/v2@v2.1.4/internal/driver/glfw/loop.go:94 +0x45
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).createWindow.func1()
	/home/lucdar/go/pkg/mod/fyne.io/fyne/v2@v2.1.4/internal/driver/glfw/window.go:1408 +0x4a
fyne.io/fyne/v2/internal/driver/glfw.runOnMain(0xc00026d890)
	/home/lucdar/go/pkg/mod/fyne.io/fyne/v2@v2.1.4/internal/driver/glfw/loop.go:55 +0xdc
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).createWindow(0xc00002e9c0, {0x9b1a9f, 0x14}, 0x1)
	/home/lucdar/go/pkg/mod/fyne.io/fyne/v2@v2.1.4/internal/driver/glfw/window.go:1407 +0xf8
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).CreateWindow(0xaa9588?, {0x9b1a9f?, 0x0?})
	/home/lucdar/go/pkg/mod/fyne.io/fyne/v2@v2.1.4/internal/driver/glfw/window.go:1399 +0x25
fyne.io/fyne/v2/app.(*fyneApp).NewWindow(0xc00002ea80?, {0x9b1a9f?, 0xd42680?})
	/home/lucdar/go/pkg/mod/fyne.io/fyne/v2@v2.1.4/app/app.go:57 +0x26
github.com/GrooveStats/gslauncher/internal/gui.NewApp(0xc00026d710, 0x0)
	/home/lucdar/gslauncher/internal/gui/gui.go:51 +0x212
main.main()
	/home/lucdar/gslauncher/cmd/gslauncher/main.go:74 +0x257
```

I've tried running the build for Linux and I got the same error. I'm not too sure what is causing it or what I can try to fix it. Any advice would be appreciated!

**Comment by natano** [comment]
Do earlier versions work for you?

**Comment by natano** [comment]
Probably related upstream issue: https://github.com/go-gl/glfw/issues/266

**Comment by lucdar** [comment]
> Do earlier versions work for you?

1.3.1 doesn't work for me either. The upstream issue mentioned earlier doesn't resolve conclusively and the user's solution didn't work.  I'm not sure how I should proceed.
