### ISSUE TITLE
Launcher doesn't start when a Teensy is connected

### ISSUE THREAD

**Issue by teejusb** [GrooveStats/gslauncher#5]
I'm on Xubuntu 64-bit. With my Teensy connected, the launcher fails to boot reporting some invalid gamepad mappings. I'm not sure if this should be fixed in the launcher or in my FSR code, but it doesn't seem problematic elsewhere so I'm wondering what causes this exception on the launcher side.

```
2021/05/10 20:02:30 GrooveStats Launcher 1.0.0 (linux amd64)
GLFW: An uncaught error has occurred: InvalidValue: Invalid button in gamepad mapping 03000000c01600008704000011010000 (Serial/Keyboard/Mouse/Joystick)
GLFW: Please report this bug in the Go package immediately.
GLFW: An uncaught error has occurred: InvalidValue: Invalid button in gamepad mapping 03000000c01600008704000011010000 (Serial/Keyboard/Mouse/Joystick)
GLFW: Please report this bug in the Go package immediately.
GLFW: An uncaught error has occurred: InvalidValue: Invalid button in gamepad mapping 03000000c01600008704000011010000 (Serial/Keyboard/Mouse/Joystick)
GLFW: Please report this bug in the Go package immediately.
GLFW: An uncaught error has occurred: InvalidValue: Invalid button in gamepad mapping 03000000c01600008704000011010000 (Serial/Keyboard/Mouse/Joystick)
GLFW: Please report this bug in the Go package immediately.
GLFW: An uncaught error has occurred: InvalidValue: Invalid button in gamepad mapping 03000000c01600008704000011010000 (Serial/Keyboard/Mouse/Joystick)
GLFW: Please report this bug in the Go package immediately.
GLFW: An uncaught error has occurred: InvalidValue: Invalid button in gamepad mapping 03000000c01600008704000011010000 (Serial/Keyboard/Mouse/Joystick)
GLFW: Please report this bug in the Go package immediately.
GLFW: An uncaught error has occurred: InvalidValue: Invalid button in gamepad mapping 03000000c01600008704000011010000 (Serial/Keyboard/Mouse/Joystick)
GLFW: Please report this bug in the Go package immediately.
GLFW: An uncaught error has occurred: InvalidValue: Invalid button in gamepad mapping 03000000c01600008704000011010000 (Serial/Keyboard/Mouse/Joystick)
GLFW: Please report this bug in the Go package immediately.
GLFW: An uncaught error has occurred: InvalidValue: Invalid button in gamepad mapping 03000000c01600008704000011010000 (Serial/Keyboard/Mouse/Joystick)
GLFW: Please report this bug in the Go package immediately.
GLFW: An uncaught error has occurred: InvalidValue: Invalid button in gamepad mapping 03000000c01600008704000011010000 (Serial/Keyboard/Mouse/Joystick)
GLFW: Please report this bug in the Go package immediately.
GLFW: An uncaught error has occurred: InvalidValue: Invalid button in gamepad mapping 03000000c01600008704000011010000 (Serial/Keyboard/Mouse/Joystick)
GLFW: Please report this bug in the Go package immediately.
GLFW: An uncaught error has occurred: InvalidValue: Invalid button in gamepad mapping 03000000c01600008704000011010000 (Serial/Keyboard/Mouse/Joystick)
GLFW: Please report this bug in the Go package immediately.
GLFW: An uncaught error has occurred: InvalidValue: Invalid button in gamepad mapping 03000000c01600008704000011010000 (Serial/Keyboard/Mouse/Joystick)
GLFW: Please report this bug in the Go package immediately.
GLFW: An uncaught error has occurred: InvalidValue: Invalid button in gamepad mapping 03000000c01600008704000011010000 (Serial/Keyboard/Mouse/Joystick)
GLFW: Please report this bug in the Go package immediately.
GLFW: An uncaught error has occurred: InvalidValue: Invalid button in gamepad mapping 03000000c01600008704000011010000 (Serial/Keyboard/Mouse/Joystick)
GLFW: Please report this bug in the Go package immediately.
GLFW: An uncaught error has occurred: InvalidValue: Invalid button in gamepad mapping 03000000c01600008704000011010000 (Serial/Keyboard/Mouse/Joystick)
GLFW: Please report this bug in the Go package immediately.
GLFW: An uncaught error has occurred: InvalidValue: Invalid button in gamepad mapping 03000000c01600008704000011010000 (Serial/Keyboard/Mouse/Joystick)
GLFW: Please report this bug in the Go package immediately.
GLFW: An uncaught error has occurred: InvalidValue: Invalid button in gamepad mapping 03000000c01600008704000011010000 (Serial/Keyboard/Mouse/Joystick)
GLFW: Please report this bug in the Go package immediately.
GLFW: An uncaught error has occurred: InvalidValue: Invalid button in gamepad mapping 03000000c01600008704000011010000 (Serial/Keyboard/Mouse/Joystick)
GLFW: Please report this bug in the Go package immediately.
GLFW: An uncaught error has occurred: InvalidValue: Invalid button in gamepad mapping 03000000c01600008704000011010000 (Serial/Keyboard/Mouse/Joystick)
GLFW: Please report this bug in the Go package immediately.
GLFW: An uncaught error has occurred: InvalidValue: Invalid button in gamepad mapping 03000000c01600008704000011010000 (Serial/Keyboard/Mouse/Joystick)
GLFW: Please report this bug in the Go package immediately.
GLFW: An uncaught error has occurred: InvalidValue: Invalid button in gamepad mapping 03000000c01600008704000011010000 (Serial/Keyboard/Mouse/Joystick)
GLFW: Please report this bug in the Go package immediately.
GLFW: An uncaught error has occurred: InvalidValue: Invalid button in gamepad mapping 03000000c01600008704000011010000 (Serial/Keyboard/Mouse/Joystick)
GLFW: Please report this bug in the Go package immediately.
GLFW: An uncaught error has occurred: InvalidValue: Invalid button in gamepad mapping 03000000c01600008704000011010000 (Serial/Keyboard/Mouse/Joystick)
GLFW: Please report this bug in the Go package immediately.
GLFW: An uncaught error has occurred: InvalidValue: Invalid button in gamepad mapping 03000000c01600008704000011010000 (Serial/Keyboard/Mouse/Joystick)
GLFW: Please report this bug in the Go package immediately.
GLFW: An uncaught error has occurred: InvalidValue: Invalid button in gamepad mapping 03000000c01600008704000011010000 (Serial/Keyboard/Mouse/Joystick)
GLFW: Please report this bug in the Go package immediately.
GLFW: An uncaught error has occurred: InvalidValue: Invalid button in gamepad mapping 03000000c01600008704000011010000 (Serial/Keyboard/Mouse/Joystick)
GLFW: Please report this bug in the Go package immediately.
GLFW: An uncaught error has occurred: InvalidValue: Invalid button in gamepad mapping 03000000c01600008704000011010000 (Serial/Keyboard/Mouse/Joystick)
GLFW: Please report this bug in the Go package immediately.
GLFW: An uncaught error has occurred: InvalidValue: Invalid button in gamepad mapping 03000000c01600008704000011010000 (Serial/Keyboard/Mouse/Joystick)
GLFW: Please report this bug in the Go package immediately.
GLFW: An uncaught error has occurred: InvalidValue: Invalid button in gamepad mapping 03000000c01600008704000011010000 (Serial/Keyboard/Mouse/Joystick)
GLFW: Please report this bug in the Go package immediately.
GLFW: An uncaught error has occurred: InvalidValue: Invalid button in gamepad mapping 03000000c01600008704000011010000 (Serial/Keyboard/Mouse/Joystick)
GLFW: Please report this bug in the Go package immediately.
GLFW: An uncaught error has occurred: InvalidValue: Invalid button in gamepad mapping 03000000c01600008704000011010000 (Serial/Keyboard/Mouse/Joystick)
GLFW: Please report this bug in the Go package immediately.
GLFW: An uncaught error has occurred: InvalidValue: Invalid button in gamepad mapping 03000000c01600008704000011010000 (Serial/Keyboard/Mouse/Joystick)
GLFW: Please report this bug in the Go package immediately.
GLFW: An uncaught error has occurred: InvalidValue: Invalid button in gamepad mapping 03000000c01600008704000011010000 (Serial/Keyboard/Mouse/Joystick)
GLFW: Please report this bug in the Go package immediately.
GLFW: An uncaught error has occurred: InvalidValue: Invalid button in gamepad mapping 03000000c01600008704000011010000 (Serial/Keyboard/Mouse/Joystick)
GLFW: Please report this bug in the Go package immediately.
GLFW: An uncaught error has occurred: InvalidValue: Invalid button in gamepad mapping 03000000c01600008704000011010000 (Serial/Keyboard/Mouse/Joystick)
GLFW: Please report this bug in the Go package immediately.
GLFW: An uncaught error has occurred: InvalidValue: Invalid button in gamepad mapping 03000000c01600008704000011010000 (Serial/Keyboard/Mouse/Joystick)
GLFW: Please report this bug in the Go package immediately.
GLFW: An uncaught error has occurred: InvalidValue: Invalid button in gamepad mapping 03000000c01600008704000011010000 (Serial/Keyboard/Mouse/Joystick)
GLFW: Please report this bug in the Go package immediately.
GLFW: An uncaught error has occurred: InvalidValue: Invalid button in gamepad mapping 03000000c01600008704000011010000 (Serial/Keyboard/Mouse/Joystick)
GLFW: Please report this bug in the Go package immediately.
GLFW: An uncaught error has occurred: InvalidValue: Invalid button in gamepad mapping 03000000c01600008704000011010000 (Serial/Keyboard/Mouse/Joystick)
GLFW: Please report this bug in the Go package immediately.
GLFW: An uncaught error has occurred: InvalidValue: Invalid button in gamepad mapping 03000000c01600008704000011010000 (Serial/Keyboard/Mouse/Joystick)
GLFW: Please report this bug in the Go package immediately.
GLFW: An uncaught error has occurred: InvalidValue: Invalid button in gamepad mapping 03000000c01600008704000011010000 (Serial/Keyboard/Mouse/Joystick)
GLFW: Please report this bug in the Go package immediately.
GLFW: An uncaught error has occurred: InvalidValue: Invalid button in gamepad mapping 03000000c01600008704000011010000 (Serial/Keyboard/Mouse/Joystick)
GLFW: Please report this bug in the Go package immediately.
GLFW: An uncaught error has occurred: InvalidValue: Invalid button in gamepad mapping 03000000c01600008704000011010000 (Serial/Keyboard/Mouse/Joystick)
GLFW: Please report this bug in the Go package immediately.
GLFW: An uncaught error has occurred: InvalidValue: Invalid button in gamepad mapping 03000000c01600008704000011010000 (Serial/Keyboard/Mouse/Joystick)
GLFW: Please report this bug in the Go package immediately.
GLFW: An uncaught error has occurred: InvalidValue: Invalid button in gamepad mapping 03000000c01600008704000011010000 (Serial/Keyboard/Mouse/Joystick)
GLFW: Please report this bug in the Go package immediately.
GLFW: An uncaught error has occurred: InvalidValue: Invalid button in gamepad mapping 03000000c01600008704000011010000 (Serial/Keyboard/Mouse/Joystick)
GLFW: Please report this bug in the Go package immediately.
GLFW: An uncaught error has occurred: InvalidValue: Invalid button in gamepad mapping 03000000c01600008704000011010000 (Serial/Keyboard/Mouse/Joystick)
GLFW: Please report this bug in the Go package immediately.
GLFW: An uncaught error has occurred: InvalidValue: Invalid button in gamepad mapping 03000000c01600008704000011010000 (Serial/Keyboard/Mouse/Joystick)
GLFW: Please report this bug in the Go package immediately.
GLFW: An uncaught error has occurred: InvalidValue: Invalid button in gamepad mapping 03000000c01600008704000011010000 (Serial/Keyboard/Mouse/Joystick)
GLFW: Please report this bug in the Go package immediately.
GLFW: An uncaught error has occurred: InvalidValue: Invalid button in gamepad mapping 03000000c01600008704000011010000 (Serial/Keyboard/Mouse/Joystick)
GLFW: Please report this bug in the Go package immediately.
GLFW: An uncaught error has occurred: InvalidValue: Invalid button in gamepad mapping 03000000c01600008704000011010000 (Serial/Keyboard/Mouse/Joystick)
GLFW: Please report this bug in the Go package immediately.
GLFW: An uncaught error has occurred: InvalidValue: Invalid button in gamepad mapping 03000000c01600008704000011010000 (Serial/Keyboard/Mouse/Joystick)
GLFW: Please report this bug in the Go package immediately.
GLFW: An uncaught error has occurred: InvalidValue: Invalid button in gamepad mapping 03000000c01600008704000011010000 (Serial/Keyboard/Mouse/Joystick)
GLFW: Please report this bug in the Go package immediately.
GLFW: An uncaught error has occurred: InvalidValue: Invalid button in gamepad mapping 03000000c01600008704000011010000 (Serial/Keyboard/Mouse/Joystick)
GLFW: Please report this bug in the Go package immediately.
GLFW: An uncaught error has occurred: InvalidValue: Invalid button in gamepad mapping 03000000c01600008704000011010000 (Serial/Keyboard/Mouse/Joystick)
GLFW: Please report this bug in the Go package immediately.
panic: InvalidValue: Invalid button in gamepad mapping 03000000c01600008704000011010000 (Serial/Keyboard/Mouse/Joystick)

goroutine 1 [running, locked to thread]:
github.com/go-gl/glfw/v3.3/glfw.acceptError(0xc00021f9d0, 0x1, 0x1, 0x42c115, 0x45f2dc)
	/root/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20210410170116-ea3d685f79fb/error.go:174 +0x225
github.com/go-gl/glfw/v3.3/glfw.Init(0x4, 0xc00021fa20)
	/root/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20210410170116-ea3d685f79fb/glfw.go:37 +0x57
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).initGLFW.func1()
	/root/go/pkg/mod/fyne.io/fyne/v2@v2.0.3/internal/driver/glfw/loop.go:70 +0x2b
sync.(*Once).doSlow(0x11ddf78, 0xc00021fa80)
	/usr/local/go/src/sync/once.go:68 +0xec
sync.(*Once).Do(...)
	/usr/local/go/src/sync/once.go:59
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).initGLFW(0xc00007b270)
	/root/go/pkg/mod/fyne.io/fyne/v2@v2.0.3/internal/driver/glfw/loop.go:69 +0x65
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).createWindow.func1()
	/root/go/pkg/mod/fyne.io/fyne/v2@v2.0.3/internal/driver/glfw/window.go:1284 +0x57
fyne.io/fyne/v2/internal/driver/glfw.runOnMain(0xc000349a10)
	/root/go/pkg/mod/fyne.io/fyne/v2@v2.0.3/internal/driver/glfw/loop.go:51 +0xb0
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).createWindow(0xc00007b270, 0xc00044d7a0, 0x1c, 0xc0002c2501, 0xc00045e3f0, 0xc00021fbc0)
	/root/go/pkg/mod/fyne.io/fyne/v2@v2.0.3/internal/driver/glfw/window.go:1283 +0xd4
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).CreateWindow(0xc00007b270, 0xc00044d7a0, 0x1c, 0xc00044d7a0, 0x1c)
	/root/go/pkg/mod/fyne.io/fyne/v2@v2.0.3/internal/driver/glfw/window.go:1275 +0x45
fyne.io/fyne/v2/app.(*fyneApp).NewWindow(0xc00045e3f0, 0xc00044d7a0, 0x1c, 0x96b982, 0x8)
	/root/go/pkg/mod/fyne.io/fyne/v2@v2.0.3/app/app.go:52 +0x47
github.com/GrooveStats/gslauncher/internal/gui.NewApp(0xc000349920, 0x1, 0x0)
	/data/internal/gui/gui.go:51 +0x1d5
main.main()
	/data/cmd/gslauncher/main.go:54 +0x2d5
```

**Comment by natano** [comment]
Maybe this issue is related to it: https://github.com/glfw/glfw/issues/1763

**Comment by natano** [comment]
I don't think I can do much about that error, because it seems to be a bug in glfw. Maybe you can work around it by somehow mapping the teensy to a different joystick config?

**Comment by natano** [comment]
The dependency chain is like this:
fyne.io/fyne/v2 v2.0.3 ->
github.com/go-gl/glfw/v3.3/glfw v0.0.0-20210410170116-ea3d685f79fb
which bundles glfw 3.3.3

**Comment by geefr** [comment]
Just a +1 on this - Mint 19.3, Teensy 4 in serial/keyboard/mouse/joystick mode here.
Slightly different trace but same behaviour.

**Comment by teejusb** [comment]
For more context, there is a mapping in glfw for teensys with that GUID: https://github.com/go-gl/glfw/blob/ea3d685f79fb0206999ffc85ca313ebf6f6b4c51/v3.3/glfw/glfw/src/mappings.h#L416
```
"03000000c01600008704000011010000,Serial/Keyboard/Mouse/Joystick,a:b12,b:b10,back:b4,dpdown:b2,dpleft:b3,dpright:b1,dpup:b0,leftshoulder:b9,leftstick:b14,lefttrigger:b6,leftx:a1,lefty:a0,rightshoulder:b8,rightstick:b15,righttrigger:b7,rightx:a2,righty:a3,start:b5,x:b13,y:b11,platform:Linux,",
```
And glfw tries to validate the joystick against that:
```cpp
// Finds a mapping based on joystick GUID and verifies element indices
//
static _GLFWmapping* findValidMapping(const _GLFWjoystick* js)
{
    _GLFWmapping* mapping = findMapping(js->guid);
    if (mapping)
    {
        int i;

        for (i = 0;  i <= GLFW_GAMEPAD_BUTTON_LAST;  i++)
        {
            if (!isValidElementForJoystick(mapping->buttons + i, js))
            {
                _glfwInputError(GLFW_INVALID_VALUE,
                                "Invalid button in gamepad mapping %s (%s)",
                                mapping->guid,
                                mapping->name);
                return NULL;
            }
        }

        for (i = 0;  i <= GLFW_GAMEPAD_AXIS_LAST;  i++)
        {
            if (!isValidElementForJoystick(mapping->axes + i, js))
            {
                _glfwInputError(GLFW_INVALID_VALUE,
                                "Invalid axis in gamepad mapping %s (%s)",
                                mapping->guid,
                                mapping->name);
                return NULL;
            }
        }
    }

    return mapping;
}
```
So if the teensy joystick is setup in a way that does not match the mapping, for example the button or axis count differs, then it will call _glfwInputError and you'll get the error in question

**Comment by natano** [comment]
Not released yet. I'll close the issue when we have it tested properly and included in an official release.

**Comment by offalynne** [comment]
That validation check in GLFW is a bit aggressive, I don't think that behavior (axis/button count mismatch) should  merit more than a warning. In any case thanks for the PR in SDL_GameControllerDB.

**Comment by natano** [comment]
Fix included in https://github.com/GrooveStats/gslauncher/releases/tag/v1.2.0.

**Comment by natano** [comment]
FTR, the commits that fixed the issue can be found here:
https://github.com/glfw/glfw/commit/201400b974b63eb7f23eb7d8563589df9c699d7c
https://github.com/glfw/glfw/commit/6876cf8d7e0e70dc3e4d7b0224d08312c9f78099
