### ISSUE TITLE
Program doesn't launch on Windows

### ISSUE THREAD

**Issue by Cxxxx100** [GrooveStats/gslauncher#8]
I installed using the gslauncher-windows-setup.exe file from the v1.1.0 release assets

The executable just seems to do nothing when I click it  (is it just mining dogecoin in the background :thinking:)

Running Windows 7 Home Premium

Let me know if there is a way to collect more debug information

Attached a screenshot of me trying to run from the command line (to rule out me being dumb and not double clicking on the shortcut correctly haha)
![Untitled2](https://user-images.githubusercontent.com/22461323/120737403-dc9db080-c4a2-11eb-9d73-d6c612a6d746.png)

**Comment by Roujo** [comment]
There's a debug version which I believe has more logging, maybe it'll help figure out what's going on. [Here](https://github.com/GrooveStats/gslauncher/releases/download/v1.1.0/gslauncher-windows-i386-debug.exe) is the 32-bit version, and [here](https://github.com/GrooveStats/gslauncher/releases/download/v1.1.0/gslauncher-windows-amd64-debug.exe) is the 64-bit one. Going by the `Program Files (x86)` in your path here, you'll want the 64-bit one. ^^

Do you get some output when you run those?

**Comment by Cxxxx100** [comment]
Here is the output when I run the debug version:

```
2021/06/04 00:59:53 GrooveStats Launcher 1.1.0 (windows amd64)
2021/06/04 00:59:53 Fyne error:  failed to initialise OpenGL
2021/06/04 00:59:53   Cause: glGetBufferParameteri64v
2021/06/04 00:59:53   At: /root/go/pkg/mod/fyne.io/fyne/v2@v2.0.3/internal/painter/gl/gl_core.go:102
Exception 0xc0000005 0x8 0x0 0x0
PC=0x0
signal arrived during external code execution

github.com/go-gl/gl/v3.2-core/gl._Cfunc_glowShaderSource(0x0, 0x100000001, 0xc0000d8078, 0x0)
        _cgo_gotypes.go:18748 +0x47
github.com/go-gl/gl/v3.2-core/gl.ShaderSource.func1(0x100000001, 0xc0000d8078, 0x0)
        /root/go/pkg/mod/github.com/go-gl/gl@v0.0.0-20210501111010-69f74958bac0/v3.2-core/gl/package.go:12294 +0x85
github.com/go-gl/gl/v3.2-core/gl.ShaderSource(0x100000001, 0xc0000d8078, 0x0)
        /root/go/pkg/mod/github.com/go-gl/gl@v0.0.0-20210501111010-69f74958bac0/v3.2-core/gl/package.go:12294 +0x4c
fyne.io/fyne/v2/internal/painter/gl.compileShader(0xb3f68d, 0xd0, 0x8b31, 0xc0005a5e60, 0x64741e, 0xe6b168)
        /root/go/pkg/mod/fyne.io/fyne/v2@v2.0.3/internal/painter/gl/gl_core.go:115 +0xcf
fyne.io/fyne/v2/internal/painter/gl.(*glPainter).Init(0xc000590030)
        /root/go/pkg/mod/fyne.io/fyne/v2@v2.0.3/internal/painter/gl/gl_core.go:163 +0x49
fyne.io/fyne/v2/internal/driver/glfw.(*window).create.func2()
        /root/go/pkg/mod/fyne.io/fyne/v2@v2.0.3/internal/driver/glfw/window.go:1344 +0xa2
fyne.io/fyne/v2/internal/driver/glfw.(*window).RunWithContext(0xc0003481c0, 0xc00058a000)
        /root/go/pkg/mod/fyne.io/fyne/v2@v2.0.3/internal/driver/glfw/window.go:1204 +0x58
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).startDrawThread.func1(0xc0005922d0, 0xc000026060, 0xc00005a050)
        /root/go/pkg/mod/fyne.io/fyne/v2@v2.0.3/internal/driver/glfw/loop.go:189 +0x145
created by fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).startDrawThread
        /root/go/pkg/mod/fyne.io/fyne/v2@v2.0.3/internal/driver/glfw/loop.go:181 +0xc8

goroutine 1 [select, locked to thread]:
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).runGL(0xc0005922d0)
        /root/go/pkg/mod/fyne.io/fyne/v2@v2.0.3/internal/driver/glfw/loop.go:90 +0x147
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).Run(0xc0005922d0)
        /root/go/pkg/mod/fyne.io/fyne/v2@v2.0.3/internal/driver/glfw/driver.go:80 +0x3e
fyne.io/fyne/v2/app.(*fyneApp).Run(0xc0003d2700)
        /root/go/pkg/mod/fyne.io/fyne/v2@v2.0.3/app/app.go:66 +0x9a
github.com/GrooveStats/gslauncher/internal/gui.(*App).Run(0xc000592370)
        /data/internal/gui/gui.go:176 +0x42
main.main()
        /data/cmd/gslauncher/main.go:75 +0x345

goroutine 19 [sleep]:
time.Sleep(0x22ecb25c00)
        /usr/local/go/src/runtime/time.go:193 +0xe5
fyne.io/fyne/v2/internal/painter.svgCacheJanitor.func1()
        /root/go/pkg/mod/fyne.io/fyne/v2@v2.0.3/internal/painter/svg_cache.go:57 +0x11d
sync.(*Once).doSlow(0xe6b158, 0xc0000ad370)
        /usr/local/go/src/sync/once.go:68 +0xf7
sync.(*Once).Do(0xe6b158, 0xc0000ad370)
        /usr/local/go/src/sync/once.go:59 +0x4c
created by fyne.io/fyne/v2/internal/painter.svgCacheJanitor
        /root/go/pkg/mod/fyne.io/fyne/v2@v2.0.3/internal/painter/svg_cache.go:55 +0xa5

goroutine 20 [select]:
fyne.io/fyne/v2/data/binding.makeInfiniteQueue.func1(0xc000086120, 0xc0000d80b0)
        /root/go/pkg/mod/fyne.io/fyne/v2@v2.0.3/data/binding/queue.go:36 +0x165
created by fyne.io/fyne/v2/data/binding.makeInfiniteQueue
        /root/go/pkg/mod/fyne.io/fyne/v2@v2.0.3/data/binding/queue.go:21 +0xb6

goroutine 21 [chan receive]:
fyne.io/fyne/v2/data/binding.processItems()
        /root/go/pkg/mod/fyne.io/fyne/v2@v2.0.3/data/binding/queue.go:54 +0x4b
created by fyne.io/fyne/v2/data/binding.init.0
        /root/go/pkg/mod/fyne.io/fyne/v2@v2.0.3/data/binding/queue.go:15 +0x3c

goroutine 5 [chan receive]:
fyne.io/fyne/v2/app.newAppWithDriver.func1(0xc000086540, 0xc0003d2700)
        /root/go/pkg/mod/fyne.io/fyne/v2@v2.0.3/app/app.go:120 +0x45
created by fyne.io/fyne/v2/app.newAppWithDriver
        /root/go/pkg/mod/fyne.io/fyne/v2@v2.0.3/app/app.go:118 +0x1e9

goroutine 6 [syscall, locked to thread]:
syscall.Syscall6(0x7708a4d0, 0x5, 0x170, 0xc000057d80, 0xc000057d20, 0xc000057dd0, 0xffffffff, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/runtime/syscall_windows.go:343 +0xf2
syscall.getQueuedCompletionStatus(0x170, 0xc000057d80, 0xc000057d20, 0xc000057dd0, 0xc0ffffffff, 0xc0000c4801, 0x6bbee5)
        /usr/local/go/src/syscall/zsyscall_windows.go:826 +0xd5
syscall.GetQueuedCompletionStatus(0x170, 0xc000057d80, 0xc000057d84, 0xc000057dd0, 0xffffffff, 0x0, 0x0)
        /usr/local/go/src/syscall/syscall_windows.go:1226 +0x7a
github.com/fsnotify/fsnotify.(*Watcher).readEvents(0xc0004a3840)
        /root/go/pkg/mod/github.com/fsnotify/fsnotify@v1.4.9/windows.go:381 +0xa5
created by github.com/fsnotify/fsnotify.NewWatcher
        /root/go/pkg/mod/github.com/fsnotify/fsnotify@v1.4.9/windows.go:46 +0x211

goroutine 7 [chan receive]:
fyne.io/fyne/v2/app.watchFile.func1(0xc0004a3840, 0xc000481540, 0x32, 0xc00058a170, 0xc00058a180)
        /root/go/pkg/mod/fyne.io/fyne/v2@v2.0.3/app/settings_desktop.go:42 +0x5f
created by fyne.io/fyne/v2/app.watchFile
        /root/go/pkg/mod/fyne.io/fyne/v2@v2.0.3/app/settings_desktop.go:41 +0xf1

goroutine 67 [chan receive]:
fyne.io/fyne/v2/internal/driver/glfw.(*window).runEventQueue(0xc0003481c0)
        /root/go/pkg/mod/fyne.io/fyne/v2@v2.0.3/internal/driver/glfw/window.go:1264 +0xbd
created by fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).createWindow.func1
        /root/go/pkg/mod/fyne.io/fyne/v2@v2.0.3/internal/driver/glfw/window.go:1289 +0x114

goroutine 68 [chan receive]:
fyne.io/fyne/v2/internal/driver/glfw.(*glCanvas).setupThemeListener.func1(0xc0000260c0, 0xc0005a8000)
        /root/go/pkg/mod/fyne.io/fyne/v2@v2.0.3/internal/driver/glfw/canvas.go:495 +0x4e
created by fyne.io/fyne/v2/internal/driver/glfw.(*glCanvas).setupThemeListener
        /root/go/pkg/mod/fyne.io/fyne/v2@v2.0.3/internal/driver/glfw/canvas.go:493 +0xb1

goroutine 37 [chan receive]:
fyne.io/fyne/v2/internal/driver/glfw.runOnDraw(...)
        /root/go/pkg/mod/fyne.io/fyne/v2@v2.0.3/internal/driver/glfw/loop.go:65
fyne.io/fyne/v2/internal/driver/glfw.(*window).create(0xc0003481c0)
        /root/go/pkg/mod/fyne.io/fyne/v2@v2.0.3/internal/driver/glfw/window.go:1342 +0x13e
sync.(*Once).doSlow(0xc0003481e0, 0xc00052bfb8)
        /usr/local/go/src/sync/once.go:68 +0xf7
sync.(*Once).Do(...)
        /usr/local/go/src/sync/once.go:59
fyne.io/fyne/v2/internal/driver/glfw.(*window).doShow(0xc0003481c0)
        /root/go/pkg/mod/fyne.io/fyne/v2@v2.0.3/internal/driver/glfw/window.go:376 +0x155
created by fyne.io/fyne/v2/internal/driver/glfw.(*window).Show
        /root/go/pkg/mod/fyne.io/fyne/v2@v2.0.3/internal/driver/glfw/window.go:364 +0x46

goroutine 38 [chan receive]:
fyne.io/fyne/v2/internal/painter.SvgCacheMonitorTheme.func1(0xc000026300)
        /root/go/pkg/mod/fyne.io/fyne/v2@v2.0.3/internal/painter/svg_cache.go:109 +0x3b
created by fyne.io/fyne/v2/internal/painter.SvgCacheMonitorTheme
        /root/go/pkg/mod/fyne.io/fyne/v2@v2.0.3/internal/painter/svg_cache.go:107 +0xa7
rax     0x0
rbx     0xc0005a5d08
rcx     0x1
rdi     0xc0005a5d08
rsi     0xc00003e780
rbp     0xc0005a5cc8
rsp     0x2934fd78
r8      0xc0000d8078
r9      0x0
r10     0x1
r11     0xff
r12     0xaabc00
r13     0xb4d310
r14     0x159
r15     0xffffffffffffffff
rip     0x0
rflags  0x10212
cs      0x33
fs      0x53
gs      0x2b
```

**Comment by natano** [comment]
Some people reported having issues like this when using outdated graphics drivers. Can you try updating to the newest GPU driver version?

**Comment by Cxxxx100** [comment]
Looks like my graphics card drivers were hilariously out of date (2011).  I'm trying to get it working, but it's slow going.  Might just end up buying a new laptop.

I think it's definitely a problem with my laptop and not the software, so I'll close the issue
